### PR TITLE
Use the images on the One Pace Discord as the cover art for the arcs.

### PR DESCRIPTION
**Pull request by Aaryaman-1409**
Hey, hope you're doing well. I brought this up the other day in the issues section https://github.com/jwueller/jellyfin-plugin-onepace/issues/1, where I wanted to use the images on the One Pace Discord as the cover art for the arcs. I've just done a bit of tinkering and managed to put something together. It doesn't need to store the image files in the repo or anything, and can directly store the files from discord in the jellyfin cache directory. If the cache is ever cleared and an image is requested, it can also redownload if needed.

There's a new settings page on the Jellyfin plugin dashboard that allows you to change the preference for source of the cover art. The plugin will still grab images from the website, but when choosing which image to save, it will prefer the version specified by the plugin settings page.

Jellyfin doesn't automatically replace images on library scans, so you'll have to go on the One Pace show -> click on refresh metadata -> replace all metadata and tick replace existing images. The process if also easily reversible. If you instead prefer to scrape directly from the website, you can change the plugin settings, and rerun the refresh metadata process. You can also go on a specific season, and do the refresh metadata process for a single arc.

I just have to warn you that I had 0 C# experience prior to this, and trying to decipher the Jellyfin plugin API documentation was a nightmare, so forgive me if the code is trash.

Also, sorry about the pull request spam, my git history was messy and I just force pushed to clean everything up.

### CODE REVIEW

**Comment by jwueller** [comment]
Thanks for your effort! Unfortunately I don't have time to review this right now, but I will get back to you once I do!

**Comment by jwueller** [comment]
> Also, sorry about the pull request spam, my git history was messy and I just force pushed to clean everything up.

By the way, you can update existing pull requests by pushing to your branch again, no need to make a new one :slightly_smiling_face:

**Comment by jwueller** [comment]
I'm very sorry about your hard work on this PR ending up unused after all after our brief discussion in #1.

Hopefully the official art will be available soon and thank you very much for your contribution!

**Comment by Aaryaman-1409** [comment]
Haha honestly don't worry about. It was a cool excuse to learn a new language so I don't mind if the work was ultimately not very fruitful

**Pull request closed without merging**
